# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/tansei/pro/vivado/ethane/ethane.cache/wt [current_project]
set_property parent.project_path /home/tansei/pro/vivado/ethane/ethane.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu105:part0:1.3 [current_project]
set_property ip_output_repo /home/tansei/pro/vivado/ethane/ethane.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/tansei/ダウンロード/a.coe
read_verilog -library xil_defaultlib -sv {
  /home/tansei/pro/vivado/ethane/ethane.srcs/sources_1/new/core.sv
  /home/tansei/pro/vivado/ethane/ethane.srcs/sources_1/new/register.sv
}
read_verilog -library xil_defaultlib /home/tansei/pro/vivado/ethane/ethane.srcs/sources_1/new/core_wrapper.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/tansei/pro/vivado/ethane/ethane.srcs/constrs_1/imports/new/kcu105.xdc
set_property used_in_implementation false [get_files /home/tansei/pro/vivado/ethane/ethane.srcs/constrs_1/imports/new/kcu105.xdc]


synth_design -top core_wrapper -part xcku040-ffva1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef core_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file core_wrapper_utilization_synth.rpt -pb core_wrapper_utilization_synth.pb"
